name: Track Core Web Vitals

on:
  schedule:
    - cron: "0 6 * * *" # runs daily at 6 AM UTC
  workflow_dispatch: # allows you to trigger manually too

jobs:
  run-vitals:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # needed for commits

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.40.3

      - name: Run Web Vitals Script
        env:
          API_KEY: ${{ secrets.PSI_API_KEY }}
        run: |
          deno run --allow-net --allow-env --allow-read --allow-write main.ts

      - name: Commit & push updated log
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add cwv-log-v3.json
          if git diff --cached --quiet; then
            echo "✅ No changes to commit."
          else
            git commit -m "🔄 Update web vitals log [bot]"
            git push
          fi
