# .github/workflows/daily-web-vitals.yml

name: Track Core Web Vitals

on:
  schedule:
    - cron: "0 6 * * *" # runs daily at 6 AM UTC
  workflow_dispatch: # allows you to trigger manually too

jobs:
  run-vitals:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x # latest Deno

      - name: Run Web Vitals Script
        env:
          API_KEY: ${{ secrets.PSI_API_KEY }}
        run: |
          deno run --allow-net --allow-env main.ts
